<?php

use common\helpers\CMyHtml;

$inputs = [
    ['type' => CMyHtml::INPUT_COMBOBOX, 'name' => 'car_id',
        'label' => '车辆型号',
        'value' => '',
        'data' => \common\components\VehicleModule::getVehicleModelNamesArrayByIds(['all' => 1]),
        'htmlOptions' => ['required' => true],
    ],
    ['type' => CMyHtml::INPUT_DATETIMEBOX, 'name' => 'start_time',
        'label' => '起租时间',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_DATETIMEBOX, 'name' => 'end_time',
        'label' => '还车时间',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_NUMBERBOX, 'name' => 'days',
        'label' => '租车天数',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_COMBOTREE, 'name' => 'sid',
        'label' => '租车门店',
        'value' => '',
        'data' => \common\components\OfficeModule::getOfficeComboTreeData(),
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_COMBOTREE, 'name' => 'return_sid',
        'label' => '还车门店',
        'value' => '',
        'data' => \common\components\OfficeModule::getOfficeComboTreeData(),
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_COMBOBOX, 'name' => 'price_type',
        'label' => '价格类型',
        'value' => '',
        'data' => \common\components\OrderModule::getPriceTypeArray(),
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_COMBOBOX, 'name' => 'ser_list',
        'label' => '增值服务',
        'value' => '',
        'data' => \common\components\OrderModule::getOptionalServiceNameArray(),
        'htmlOptions' => ['multiple'=>true, 'separator'=>'|', 'editable'=>true],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'inv_title',
        'label' => '发票抬头',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'inv_name',
        'label' => '发票单位/个人名称',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'inv_phone',
        'label' => '发票手机号码',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'inv_address',
        'label' => '发票地址',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'inv_postcode',
        'label' => '发票邮编',
        'value' => '',
        'htmlOptions' => [],
    ],
    ['type' => CMyHtml::INPUT_TEXTBOX, 'name' => 'sign',
        'label' => 'sign',
        'value' => '',
        'htmlOptions' => [],
    ],
];

$buttons = ['submit' => Yii::t('locale', 'Submit'), 'close' => Yii::t('locale', 'Cancel')];

$hiddenFields = ['action' => 'save', 'card_type'=>1];

echo CMyHtml::form('测试下单', \yii\helpers\Url::to(['order/order']), 'post', 
    [
        'successCallback' => "function (data) {\n".
            "    $.custom.easyui.alert.show(data, 'Result', 'info', 'info');\n".
            "\n}",
    ], $inputs, $buttons, $hiddenFields);
